# SSIS Migration Tool Configuration

# Database configuration
database:
  host: localhost
  port: 1433
  database: master
  username: ""
  password: ""
  driver: "ODBC Driver 17 for SQL Server"
  timeout: 30

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/ssis_migrator.log
  max_size: 10485760  # 10MB
  backup_count: 5

# Conversion configuration
conversion:
  output_format: python
  include_tests: true
  include_docs: true
  backup_original: true
  validate_output: true
  parallel_processing: false
  max_workers: 4

# Environment settings
environment: development
debug: false 